#!/bin/sh

# Info 
about="package manager for openBSD\n"
ver="0.3\n"
maintainer="hexisXz/Quinn Kelly\n"
name="openpkg\n"

# Colors
RESET=$(printf '\033[0m')
BOLD=$(printf '\033[1m')
UNDERLINE=$(printf '\033[4m')
BLACK=$(printf '\033[30m')
RED=$(printf '\033[31m')
GREEN=$(printf '\033[32m')
YELLOW=$(printf '\033[33m')
BLUE=$(printf '\033[34m')
MAGENTA=$(printf '\033[35m')
CYAN=$(printf '\033[36m')
WHITE=$(printf '\033[37m')
BG_BLACK=$(printf '\033[40m')
BG_RED=$(printf '\033[41m')
BG_GREEN=$(printf '\033[42m')
BG_YELLOW=$(printf '\033[43m')
BG_BLUE=$(printf '\033[44m')
BG_MAGENTA=$(printf '\033[45m')
BG_CYAN=$(printf '\033[46m')
BG_WHITE=$(printf '\033[47m')

# Clean install & uninstall scripts off of the system
clean() {
  rm -f uninstall install
}

# Install a package
install() {
  clean
  if [ -z "$2" ]; then
    printf "${RED}No package name provided for installation.\n"
    exit 1
  fi
  printf "${GREEN}INSTALLING ${BOLD}$2${RESET}${GREEN}...\n"
  ftp -m -C "https://raw.githubusercontent.com/hexisXz/openpkg-repo/main/$2/install" && chmod +x install && sh install
  printf "${GREEN}DONE\n"
  clean
}

# Uninstall a package 
uninstall() {
  if [ -z "$2" ]; then
    printf "${RED}No package name provided for uninstallation.\n"
    exit 1
  fi
  printf "${RED}ARE YOU SURE YOU WANT TO REMOVE ${BOLD}$2${RESET}${RED} (y/n)?\n"
  read -r i
  if [ "$i" = "y" ]; then
    ftp -m -C "https://raw.githubusercontent.com/hexisXz/openpkg-repo/main/$2/uninstall" && chmod +x uninstall && sh uninstall && clean
    printf "${RED}$2 HAS BEEN REMOVED\n"
  else
    printf "${RED}$2 HAS NOT BEEN REMOVED\n"
  fi
}

# Help
hlp() {
  printf "${BLUE}-i <package_name> (install a package)
-h (display help commands)
-c (clean {remove the install & uninstall scripts})
-R <package_name> (uninstall/remove a package)
-v (version)\n"
}

# Flags
case "$1" in
  -i) install "$@" ;;
  -R) uninstall "$@" ;;
  -c) clean ;;
  -h) hlp ;;
  -v) printf "$ver\n" ;;
  *) hlp ;;
esac
