#!/bin/sh

#info 
about="package manager for openBSD\n"
ver="0.3\n"
maintainer="hexisXz/Quinn Kelly\n"
name="openpkg\n"

# colors
RESET=$(printf '\033[0m')
BOLD=$(printf '\033[1m')
UNDERLINE=$(printf '\033[4m')
BLACK=$(printf '\033[30m')
RED=$(printf '\033[31m')
GREEN=$(printf '\033[32m')
YELLOW=$(printf '\033[33m')
BLUE=$(printf '\033[34m')
MAGENTA=$(printf '\033[35m')
CYAN=$(printf '\033[36m')
WHITE=$(printf '\033[37m')
BG_BLACK=$(printf '\033[40m')
BG_RED=$(printf '\033[41m')
BG_GREEN=$(printf '\033[42m')
BG_YELLOW=$(printf '\033[43m')
BG_BLUE=$(printf '\033[44m')
BG_MAGENTA=$(printf '\033[45m')
BG_CYAN=$(printf '\033[46m')
BG_WHITE=$(printf '\033[47m')


#clean install & uninstall scripts off of the system
clean() {
  rm uninstall && rm install
}

#install a package
install() {
  clean
  printf "${GREEN}INSTALLING...\n"
  ftp -m -C https://raw.githubusercontent.com/hexisXz/openpkg-repo/main/$3/install && chmod +x install && sh install
  printf "${GREEN}DONE\n"
  clean
}

#uninstall a package 
uninstall() {
  printf "${RED}ARE YOU SURE YOU WANT TO REMOVE $2 (y/n)\n"
  read i
  if [ "$i" = "y" ]; then
    ftp -m -C https://raw.githubusercontent.com/hexisXz/openpkg-repo/main/$3/uninstall && chmod +x uninstall && sh uninstall && clean
    printf "${RED}$2 HAS been removed\n"
  else
    printf "${RED}$2 has NOT been removed\n"
  fi
}

#help
hlp() {
  printf "${BLUE}-i (install a package)
-h (display help commands)
-c (clean {meaning remove the install & uninstall scripts})
-R (uninstall/remove a package)
-v (version)\n"
}

#flags
case "$1" in
  -i) install
  ;;
  -R) uninstall
  ;;
  -C) clean
  ;;
  -h) hlp
  ;;
  -v) printf "$ver"
  ;;
  *) hlp
  ;;
esac
